# Generated by Django 2.2.4 on 2019-09-04 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0001_initial'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='favoritos', serialize=False, to='cliente.Cliente', verbose_name='Cliente')),
                ('produto', models.ManyToManyField(blank=True, related_name='favoritos', to='produto.Produto', verbose_name='Produtos')),
            ],
        ),
    ]
